version: "2.4"

services:
  server:
    container_name: trueconf-server
    image: ${TC_IMAGE_TAG}
    restart: unless-stopped
    network_mode: host
    environment:
      - ADMIN_USER=${ADMIN_LOGIN:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-trueconf}
      - DUMP_PATH=/opt/trueconf/server/var/lib/dump
    volumes:
      - ./data:/opt/trueconf/server/var/lib